--EJERCICIO 1
SELECT
     UPPER (NOMBRE) || ' ' || INITCAP (APELLIDO_PATERNO) || ' '  || INITCAP (APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
     LENGTH (NOMBRE) + LENGTH (APELLIDO_PATERNO) + LENGTH (APELLIDO_MATERNO) AS "LARGO_NOMBRE",
     SUBSTR (NOMBRE, 1, 1) ||'.' || SUBSTR (APELLIDO_PATERNO, 1,1) || '.' || + SUBSTR (APELLIDO_MATERNO, 1,1) AS "INICIALES"
     FROM CLIENTE_CINE
WHERE NOMBRE LIKE 'C%';

--- EJERCICIO 2

SELECT
    TITULO "TITULO",
    'La pelicula tiene una duracion de ' || DURACION_MIN || ' minutos' "DURACION",
    TRUNC (DURACION_MIN / 60) "HORAS",
    MOD (DURACION_MIN , 60) "MINUTOS",
    TRUNC (DURACION_MIN / 60) || ' HRS ' || LPAD(MOD(DURACION_MIN , 60), 2, '0') || ' MIN '
FROM
    PELICULA
WHERE
    FECHA_ESTRENO < '11/09/2025';
    
--EJERCICIO 3

SELECT 
    TO_CHAR 

FROM FUNCION_CINE



    
    





    
    