--EJERCICIO 1
SELECT
     UPPER (NOMBRE) || ' ' || INITCAP (APELLIDO_PATERNO) || ' '  || INITCAP (APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
     LENGTH (NOMBRE) + LENGTH (APELLIDO_PATERNO) + LENGTH (APELLIDO_MATERNO) AS "LARGO_NOMBRE",
     SUBSTR (NOMBRE, 1, 1) ||'.' || SUBSTR (APELLIDO_PATERNO, 1,1) || '.' || + SUBSTR (APELLIDO_MATERNO, 1,1) AS "INICIALES"
     FROM CLIENTE_CINE
WHERE NOMBRE LIKE 'C%';

--- EJERCICIO 2

SELECT
    TITULO "TITULO",
    'La pelicula tiene una duracion de ' || DURACION_MIN || ' minutos' "DURACION",
    TRUNC (DURACION_MIN / 60) "HORAS",
    MOD (DURACION_MIN , 60) "MINUTOS",
    TRUNC (DURACION_MIN / 60) || ' HRS ' || LPAD(MOD(DURACION_MIN , 60), 2, '0') || ' MIN '
FROM
    PELICULA
WHERE
    FECHA_ESTRENO < '11/09/2025';
    
--EJERCICIO 3

SELECT 
    TO_CHAR (FECHA, 'DD"-"MM"-"YYYY hh24:mi') "FECHA FUNCION",
    TRIM (TO_CHAR(FECHA, 'DAY')) "DIA_SEMANA",
CASE
    WHEN TO_NUMBER (TO_CHAR (FECHA, 'HH24')) BETWEEN 0 AND 15 THEN 'MATINE'
    WHEN TO_NUMBER (TO_CHAR (FECHA, 'HH24')) BETWEEN 16 AND 20 THEN 'TARDE'
    WHEN TO_NUMBER (TO_CHAR (FECHA, 'HH24')) BETWEEN 21 AND 23 THEN 'NOCHE'
END AS FRANJA_HORARIA,
DECODE  
    (NVL (ID_SALA, 0), 1, 'SALA 1', 2, 'SALA 2', 3, 'SALA 3', 4, 'SALA4', 'SALA DESCONOCIDA') AS SALA
FROM FUNCION_CINE
    WHERE TRUNC(FECHA) = TO_DATE ('&FECHA_BUSQUEDA',' DD-MM-YYYY')
    ORDER BY fecha;


    
    





    
    
