SELECT
    NUMFACTURA "NUMERO DE FACTURA",
    TO_CHAR(FECHA, 'DD "DE" MONTH YYYY') "FECHA DE EMISION",
    LPAD (RUTCLIENTE,10,0) "RUT CLIENTE",
    TO_CHAR(NETO,'$9999999') AS "MONTO NETO",
    TO_CHAR(IVA,'$99999999') AS "MONTO IVA",
    TO_CHAR (TOTAL,'$9999999') AS "TOTAL FACTURA",
    
    CASE 
        WHEN TOTAL BETWEEN 0 AND 50000 THEN 'BAJO'
        WHEN TOTAL BETWEEN 50001 AND 100000 THEN 'MEDIO'
        ELSE 'ALTO'
    END AS "CATEGORIA MONTO",
    CASE 
        WHEN CODPAGO = 1 THEN 'EFECTIVO'
        WHEN CODPAGO = 2 THEN 'TARJETA DEBITO'
        WHEN CODPAGO = 3 THEN 'TARJETA DE CREDITO'
        WHEN CODPAGO = 4 THEN 'CHEQUE'
    END "FORMA DE PAGO"
    FROM FACTURA 
    WHERE 
        EXTRACT (YEAR FROM FECHA) = EXTRACT (YEAR FROM SYSDATE)-1
    ORDER BY FECHA DESC, "MONTO NETO" DESC;
    
    ---CASO 2
    
SELECT 
    LPAD (RUTCLIENTE,12,'*') AS "RUT",
    INITCAP(NOMBRE)          AS "Cliente",
    --Manejo de teléfono y comuna nulos:
    NVL(TO_CHAR(TELEFONO), 'Sin telefono') AS Telefono, 
    DECODE(CODCOMUNA, NULL, 'SIN COMUNA', TO_CHAR(CODCOMUNA)) AS Comuna,
    ESTADO, 
    --CATEGORIZAR CREDITO:
    CASE 
        WHEN SALDO / CREDITO < 0.5 THEN 'BUENO(' || TO_CHAR (CREDITO - SALDO, '$9999999') || ')'
        WHEN SALDO / CREDITO BETWEEN 0.5 AND 0.8 THEN 'REGULAR (' || TO_CHAR(SALDO, '$9G999G999') || ')'
        ELSE 'CRITICO'
    END AS "ESTADO CREDITO",
    
    --VALIDAR CORREOS:
    
    DECODE (MAIL, 
        NULL, 'Correo no registado', 
        SUBSTR(MAIL, INSTR(MAIL,'@') + 1)) AS "DOMINIO CORREO"
    FROM CLIENTE
    WHERE 
        (ESTADO = 'A' AND CREDITO >0)
    ORDER BY 
        NOMBRE ASC;
        
        
        -- CASO 3
        
SELECT 
    CODPRODUCTO AS "ID",
    INITCAP(DESCRIPCION) AS "DESCRIPCION DE PRODUCTO",
    LPAD(NVL2(TO_CHAR(valorcompradolar),TO_CHAR(valorcompradolar) ||'USD','SIN REGISTRO'),15,' ') AS "
    LPAD (NVL2(TO_CHAR(valorcompradolar),TO_CHAR(ROUND(VALORCOMPRADOLAR * &TIPOCAMBIO_DOLAR),'$999g999')
    TOTALSTOCK AS "STOCK",
--VALIDACION STOCK

    CASE 
        WHEN TOTALSTOCK IS NULL THEN 'SIN DATOS'
        WHEN TOTALSTOCK < &UMBRAL_BAJO THEN '¡ALERTA STOCK MUY BAJO!'
        WHEN TOTALSTOCK BETWEEN &UMBRAL_ALTO THEN '¡REABASTECER PRONTO!'
        ELSE 'OK'
    END AS "ALERTA STOCK",
    
    -- DESCUENTO SUGERIDO
    
    LPAD (CASE
        WHEN TOTALSTOCK > 80 THEN TO_CHAR(VUNITARIO * 0.9, '$999G999')
        ELSE 'N/A'
    END,10, ' ') AS "PRECIO OFERTA"
FROM PRODUCTO
WHERE 
    DESCRIPCION LIKE 'ZAPATO%' AND PROCEDENCIA = 'I'
    PRDER BY "ID" DESC;

    