--EJERCICIO 1
SELECT APELLIDO "APELLIDO DEL EMPLEADO",
OFICIO "CARGO EN LA EMPRESA",
DEPT_NO "DEPARTAMENTO ASIGNADO",
SALARIO * 1.05 "SALARIO + 5% INCREMENTO"
FROM EMPLE
ORDER BY APELLIDO ASC, DEPT_NO DESC;

--EJERCICIO 2

SELECT 
DEPT_NO "NUMERO DE DEPARTAMENTO",
DNOMBRE "NOMBRE DEL DEPARTAMENTO",
LOC "UBICACION GEOGRAFICA"
FROM DEPART
WHERE LOC NOT IN ('MADRID', 'BILBAO');

--EJERCICIO 3
SELECT 
    DEPT_NO AS "DEPARTAMENTO",
    EMP_NO || ' - ' || APELLIDO AS "EMPLEADO",
    SALARIO AS "SALARIO ACTUAL",
    SALARIO * 1.08 AS "INCREMENTO ANTIGUEDAD",
    SALARIO * 0.9991 AS "DESCUENTO MULTAS",
    OFICIO AS "CARGO"
    FROM EMPLE
WHERE 
    SALARIO > 200000 OR DEPT_NO IN (20,30)
ORDER BY DEPT_NO DESC;

--EJERCICIO 4

SELECT 
    APELLIDO "EMPLEADO",
    OFICIO "CARGO",
    SALARIO "SUELDO ACTUAL",
    SALARIO + 25000 "SUELDO CON BONO"
FROM EMPLE
WHERE APELLIDO LIKE 'A%' AND OFICIO LIKE '%E%'
AND SALARIO < 300000
ORDER BY SALARIO ASC;

---EJERCICIO 5
SELECT 
    EMP_NO "CODIGO DEL EMPLEADO",
    APELLIDO "APELLIDO DEL EMPLEADO",
    OFICIO "CARGO",
    SALARIO AS "SALARIO BASE",
    SALARIO + (SALARIO * 0.07) "SALARIO CON INCREMENTO",
    FECHA_INGRESO "FECHA DE INGRESO"
FROM EMPLE
WHERE OFICIO = 'EMPLEADO'
AND SALARIO < 300000
AND DEPT_NO IN (10,20)
AND FECHA_INGRESO < '01-01-2015'
ORDER BY "SALARIO BASE" DESC;

---EJERCICIO 6

SELECT
    APELLIDO "EMPLEADO SIN COMISION",
    OFICIO "PUESTO DE TRABAJO",
    COMISION "SIN COMISION",
    SALARIO "SALARIO BASE",
    SALARIO + (SALARIO * 1.15) "SALARIO CON AJUSTE",
    FECHA_INGRESO "FECHA DE INGRESO"
FROM EMPLE
WHERE 
COMISION IS NULL
AND FECHA_INGRESO BETWEEN '01-01-2005' AND '31-12-2015'
OR APELLIDO LIKE 'J%'
ORDER BY FECHA_INGRESO DESC;

---EJERCICIO 7
SELECT
APELLIDO "APELLIDO",
EMP_NO
FROM EMPLE
WHERE 
APELLIDO LIKE '%Z'
AND SALARIO > 300000
AND COMISION IS NULL





