SELECT
    TRUNC (FECHA) "DIA",
    COUNT(*) AS "VENTAS_DIA",
    TO_CHAR (MIN(FECHA),'HH:MI:SS') AS "PRIMERA VENTA",
    TO_CHAR (MAX(FECHA),'HH:MI:SS') AS "ULTIMA VENTA"
FROM VENTA
WHERE TRUNC(FECHA) >= TO_DATE('&FECHA_BUSQUEDA','DD-MM-YYYY')
GROUP BY TRUNC(FECHA)
HAVING COUNT (*) >=1
ORDER BY DIA;

